### ISSUE TITLE
Co-maintainer offer

### ISSUE THREAD

**Issue by shadowspawn** [minimistjs/minimist#1]
I am interested in being a co-maintainer of Minimist to provide some redundancy and extra expertise.

I have a particular interest in CLI. I maintain Commander.js, and helped develop parseArgs which is now included in Node.js. I have been watching Minimist for a couple of years to see what issues were coming up, and have done some digging in the code while researching behaviours across multiple CLIs.

(I know you already know my credentials @ljharb , but applying in the open!)

**Comment by ljharb** [comment]
Sounds great, let's wait a bit to see if I can recover the original minimist repo with issues/PRs, but once that's resolved one way or the other, I'll add you to the relevant places.

**Comment by boywithkeyboard** [comment]
@ljharb what happened to the old repository btw?

**Comment by ljharb** [comment]
@unvented the original author deleted their github, and thus all the associated repositories.

**Comment by boywithkeyboard** [comment]
> @unvented the original author deleted their github, and thus all the associated repositories.

oh ok 🙁

**Comment by shadowspawn** [comment]
I am still interested in Minimist. It has been a couple of months, so I expect the original repo with issues is not coming back?

**Comment by ljharb** [comment]
I think that's a safe expectation. I'll add you to the repo!

**Comment by shadowspawn** [comment]
I now have maintainer access on GitHub (thanks). But have no access on npmjs.com yet, so I couldn't do a release if you were unavailable for a long time.

I would like to also be a lifter for Minimist on TideLift. (Don't know if you had thought of that, so raising it before I do anything about it!)

Plans: I have one more historical bug in Minimist I would like to investigate and hopefully fix (bad numeric conversions for large "numbers"), and interested in discussing when and how we might release current PR, but not in any rush. The issues are all very long-standing.

**Comment by ljharb** [comment]
@shadowspawn let's chat about that stuff on a call sometime this week.

**Comment by shadowspawn** [comment]
Update: I had a good chat with @ljharb about outlook on Minimist in particular and package maintenance in general. Jordan was very gracious about me onboarding to Minimist. I have write access to git and npm so capable of independently publishing a release, if necessary. (I won't be publishing normally.)
