### ISSUE TITLE
GitHub action checks on PR always show failure

### ISSUE THREAD

**Issue by shadowspawn** [minimistjs/minimist#19]
The pull requests all show a red x from the checks. I am not sure if this is because of the failing build for Node.js 0.6, or because of the "!" messages? 

If it it due to 0.6 then I vote for disabling that test to reduce the noise! I haven't worked out an easy way to scan the failing checks for ones I caused rather than failures due to the action itself.

-----

From a recent build, it looks like nvm fails to install 0.6 rather than because the tests fail on 0.6 as such:
- https://github.com/minimistjs/minimist/actions/runs/3851691747/jobs/6563180275

I see there is an old issue open on the action: https://github.com/ljharb/actions/issues/1

**Comment by ljharb** [comment]
Yes, it's due to 0.6, and it's also due to github actions lacking the otherwise-universal CI feature of "allow failure".
