### ISSUE TITLE
About  minimist

### ISSUE THREAD

**Issue by fredgan** [minimistjs/minimist#22]
Hi @ljharb 
Excuse me to ask that whether this project was ever the project `https://github.com/substack/minimist` which is  gone now with 404.

I'm not familiar with this project. Any ideas are very appreciated!

**Comment by shadowspawn** [comment]
Yes this is the same project. Taking over maintenance now that substack is gone.

**Comment by ljharb** [comment]
Yep, exactly right.

@fredgan you can confirm that by looking at the various npm releases and the github repo they refer to.
