### ISSUE TITLE
A boolean's default value does not work when an alias is used

### ISSUE THREAD

**Issue by rDr4g0n** [minimistjs/minimist#29]
When a boolean with an alias uses the alias to define the default value, the default is not applied. This would not be bug-worthy if all defaults required using the actual flag name instead of an aliased name, but defaulting string flags works fine with aliased names. This produces some inconsistency in the behavior of the app as string vs boolean differ.

It seems that boolean defaults are only looked up by their actual flag name and does not include lookups by their aliased name: https://github.com/minimistjs/minimist/blob/main/index.js#L132-L134

Here is a repro for the bug:

```javascript
#!/usr/bin/env node

const argv = require("minimist")(process.argv.slice(2), {
  boolean: ["a-boolean"],
  alias: {
    "a-boolean": "aBoolean",
  },
  default: {
    aBoolean: true,
  },
});
```
And the results:

```
$ ./index.js
received args: [ ]
parsed args: { _: [ ], 'a-boolean': false, 'aBoolean': false }
```

Here is a workaround (not using the aliased name) that avoids the bug:

```javascript
#!/usr/bin/env node

const argv = require("minimist")(process.argv.slice(2), {
  boolean: ["a-boolean"],
  alias: {
    "a-boolean": "aBoolean",
  },
  default: {
    'a-boolean': true,
  },
});
```
And the results:

```
$ ./index.js
received args: [ ]
parsed args: { _: [ ], 'a-boolean': true, 'aBoolean': true }
```

**Comment by shadowspawn** [comment]
Thanks for clear description and reproduction.

In most cases the key and aliases can be used interchangeably. I agree it feels like a bug.
