### ISSUE TITLE
UI-UX: adding waypoint

### ISSUE THREAD

**Issue by macintoshee** [minimistjs/minimist#35]
There is quite a big difference between how users expect UI to work and how it works - the learning curve is too big and many users abandon Furkot. 

The most important problem to fix: 
adding a new waypoint from the side menu is currently the most unintuitive way possible. 
Users should be able to add waypoints just by clicking on the map and defining the waypoint and its type.

**Examples**
Komoot.
![image](https://user-images.githubusercontent.com/11297610/227880108-88777976-16e6-4ef8-a651-f3db12d0683d.png)

Roadtrippers
![image](https://user-images.githubusercontent.com/11297610/227880686-fb7ec720-3fe9-46b1-ad7a-33e3a940dd3b.png)

**Comment by shadowspawn** [comment]
You appear to have created this issue in the wrong repository.

**Comment by macintoshee** [comment]
Yes, sorry, indeed.
