### ISSUE TITLE
UI-UX: remove clutter from sidepanel

### ISSUE THREAD

**Issue by macintoshee** [minimistjs/minimist#36]
Remove clutter from the plan tab. There is too much information at first, it needs better organization and better hierarchy. User should be able to choose more information when needed. Otherwise, it's noise.

Example of how it could be below from Roadtrippers. It's not 1:1 suitable to take over as it takes too much place but the general idea is good and very easy to understand. If needed I can deliver UI-UX for that part.

![image](https://user-images.githubusercontent.com/11297610/227883145-a988bc2a-1688-4075-a21f-9b85994d06a7.png)

**Comment by shadowspawn** [comment]
You appear to have created this issue in the wrong repository. The furkot organisation is at: https://github.com/furkot
