### ISSUE TITLE
Repeated occurence of `=` isnt handled correctly

### ISSUE THREAD

**Issue by nhz-io** [minimistjs/minimist#5]
### minimist doesn't handle correctly:
```
-a=b=c
{ _: [], a: 'b' }
```

### yargs-parser does handle correctly
```
-a=b=c
{ _: [], a: 'b=c' }
```

Spawned from: https://github.com/minimistjs/minimist/issues/2#issuecomment-1279851737

**Comment by shadowspawn** [comment]
I think there are _two_ bugs in this area of the code. The code is looking for an `=` but not restricting test to just the start of the argument, then assumes there is only one `=` when assigning the option value.

So the second bug is with `-ab=c` the `b` is getting ignored.

https://github.com/minimistjs/minimist/blob/980d7ac61a0b4bd552711251ac107d506b23e41f/index.js#L152

https://github.com/minimistjs/minimist/blob/980d7ac61a0b4bd552711251ac107d506b23e41f/index.js#L153
