### ISSUE TITLE
Browser support leftovers in package.json

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [minimistjs/minimist#56]
Hi guys, I was checking out this repo's `package.json` and I saw that there is this ["testling" block](https://github.com/minimistjs/minimist/blob/main/package.json#L29) with various browser versions for this package. This is a nodejs application for parsing command line arguments, there is no need to keep that section in there as far as I know.

I did some digging around in the git history and found that it was added to the original repo 10 years ago in this commit: https://github.com/minimistjs/minimist/commit/84c037063664d42878aace715fe6572ce01b6f3b

Notice that the readme also contained a browser support badge, which was removed in 2020 by substack in this commit: https://github.com/minimistjs/minimist/commit/67d3722413448d00a62963d2d30c34656a92d7e2

It looks like the `testling` part was forgotten and accidentally left in there.

**Comment by ljharb** [comment]
Sure, it does no harm by being there but it’s fine to remove it.

**Comment by shadowspawn** [comment]
(Thanks for digging into the history.)

**Comment by ljharb** [comment]
In 6715df1360048b44db868ed04d60f5ab9203aeff i removed `browsers`, since the testling service is dead. However, I still use the `testling` cli package, which requires the `files` key, so that remains.
