### ISSUE TITLE
[Enhancement] Need ESM support

### ISSUE THREAD

**Issue by Tetrax-10** [minimistjs/minimist#58]
Thanks for this awesome light weight argv parser. Just discovered it but unfortunately I can't use this in [my project](https://github.com/Tetrax-10/stash-plugin-builder) as this package doesn't support ESM. It would be nice if ESM import is supported. Thanks.

This doesn't work
```js
import minimist from "minimist"

const argv = minimist(process.argv.slice(2))
```

**Comment by ljharb** [comment]
What doesn't work about it? node can import CJS just fine.

**Comment by Tetrax-10** [comment]
Am so sorry it works fine now, I dont know why it didn't work last time prob my typescript... am tripin... nvm

Thanks for the package and quick reply ❤️.
