### ISSUE TITLE
Duplicate tests

### ISSUE THREAD

**Issue by nhz-io** [minimistjs/minimist#8]
https://github.com/minimistjs/minimist/blob/980d7ac61a0b4bd552711251ac107d506b23e41f/test/dash.js#L22-L23

**Comment by ljharb** [comment]
This seems intentionally added in b465514, although i can't imagine why both would be needed.

**Comment by shadowspawn** [comment]
I suspect a copy-paste with another idea in mind, that didn't get turned into a different test.

We could test `[ '-ca', '--', 'b' ]` and check end option in option group plays by same rules?

Edit: or just delete duplicate.
